In [68]:
import os

# Using raw string
folder_path = r'C:\Users\HP\data'

if os.path.exists(folder_path):  # Check if the folder exists
    filenames = [os.path.join(folder_path, file) for file in os.listdir(folder_path)]
    print(filenames)
else:
    print("Error: Folder does not exist!")

['C:\\Users\\HP\\data\\.ipynb_checkpoints', 'C:\\Users\\HP\\data\\1082591.yaml', 'C:\\Users\\HP\\data\\1082592.yaml', 'C:\\Users\\HP\\data\\1082593.yaml', 'C:\\Users\\HP\\data\\1082594.yaml', 'C:\\Users\\HP\\data\\1082595.yaml', 'C:\\Users\\HP\\data\\1082596.yaml', 'C:\\Users\\HP\\data\\1082597.yaml', 'C:\\Users\\HP\\data\\1082598.yaml', 'C:\\Users\\HP\\data\\1082599.yaml', 'C:\\Users\\HP\\data\\1082600.yaml', 'C:\\Users\\HP\\data\\1082601.yaml', 'C:\\Users\\HP\\data\\1082602.yaml', 'C:\\Users\\HP\\data\\1082603.yaml', 'C:\\Users\\HP\\data\\1082604.yaml', 'C:\\Users\\HP\\data\\1082605.yaml', 'C:\\Users\\HP\\data\\1082606.yaml', 'C:\\Users\\HP\\data\\1082607.yaml', 'C:\\Users\\HP\\data\\1082608.yaml', 'C:\\Users\\HP\\data\\1082609.yaml', 'C:\\Users\\HP\\data\\1082610.yaml', 'C:\\Users\\HP\\data\\1082611.yaml', 'C:\\Users\\HP\\data\\1082612.yaml', 'C:\\Users\\HP\\data\\1082613.yaml', 'C:\\Users\\HP\\data\\1082614.yaml', 'C:\\Users\\HP\\data\\1082615.yaml', 'C:\\Users\\HP\\data\\1082616.yaml', 'C:\\Users\\HP\\data\\1082617.yaml', 'C:\\Users\\HP\\data\\1082618.yaml', 'C:\\Users\\HP\\data\\1082620.yaml', 'C:\\Users\\HP\\data\\1082621.yaml', 'C:\\Users\\HP\\data\\1082622.yaml', 'C:\\Users\\HP\\data\\1082623.yaml', 'C:\\Users\\HP\\data\\1082624.yaml', 'C:\\Users\\HP\\data\\1082625.yaml', 'C:\\Users\\HP\\data\\1082626.yaml', 'C:\\Users\\HP\\data\\1082627.yaml', 'C:\\Users\\HP\\data\\1082628.yaml', 'C:\\Users\\HP\\data\\1082629.yaml', 'C:\\Users\\HP\\data\\1082630.yaml', 'C:\\Users\\HP\\data\\1082631.yaml', 'C:\\Users\\HP\\data\\1082632.yaml', 'C:\\Users\\HP\\data\\1082633.yaml', 'C:\\Users\\HP\\data\\1082634.yaml', 'C:\\Users\\HP\\data\\1082635.yaml', 'C:\\Users\\HP\\data\\1082636.yaml', 'C:\\Users\\HP\\data\\1082637.yaml', 'C:\\Users\\HP\\data\\1082638.yaml', 'C:\\Users\\HP\\data\\1082639.yaml', 'C:\\Users\\HP\\data\\1082640.yaml', 'C:\\Users\\HP\\data\\1082641.yaml', 'C:\\Users\\HP\\data\\1082642.yaml', 'C:\\Users\\HP\\data\\1082643.yaml', 'C:\\Users\\HP\\data\\1082644.yaml', 'C:\\Users\\HP\\data\\1082645.yaml', 'C:\\Users\\HP\\data\\1082646.yaml', 'C:\\Users\\HP\\data\\1082647.yaml', 'C:\\Users\\HP\\data\\1082648.yaml', 'C:\\Users\\HP\\data\\1082649.yaml', 'C:\\Users\\HP\\data\\1082650.yaml', 'C:\\Users\\HP\\data\\1136561.yaml', 'C:\\Users\\HP\\data\\1136562.yaml', 'C:\\Users\\HP\\data\\1136563.yaml', 'C:\\Users\\HP\\data\\1136564.yaml', 'C:\\Users\\HP\\data\\1136565.yaml', 'C:\\Users\\HP\\data\\1136566.yaml', 'C:\\Users\\HP\\data\\1136567.yaml', 'C:\\Users\\HP\\data\\1136568.yaml', 'C:\\Users\\HP\\data\\1136569.yaml', 'C:\\Users\\HP\\data\\1136570.yaml', 'C:\\Users\\HP\\data\\1136571.yaml', 'C:\\Users\\HP\\data\\1136572.yaml', 'C:\\Users\\HP\\data\\1136573.yaml', 'C:\\Users\\HP\\data\\1136574.yaml', 'C:\\Users\\HP\\data\\1136575.yaml', 'C:\\Users\\HP\\data\\1136576.yaml', 'C:\\Users\\HP\\data\\1136577.yaml', 'C:\\Users\\HP\\data\\1136578.yaml', 'C:\\Users\\HP\\data\\1136579.yaml', 'C:\\Users\\HP\\data\\1136580.yaml', 'C:\\Users\\HP\\data\\1136581.yaml', 'C:\\Users\\HP\\data\\1136582.yaml', 'C:\\Users\\HP\\data\\1136583.yaml', 'C:\\Users\\HP\\data\\1136584.yaml', 'C:\\Users\\HP\\data\\1136585.yaml', 'C:\\Users\\HP\\data\\1136586.yaml', 'C:\\Users\\HP\\data\\1136587.yaml', 'C:\\Users\\HP\\data\\1136588.yaml', 'C:\\Users\\HP\\data\\1136589.yaml', 'C:\\Users\\HP\\data\\1136590.yaml', 'C:\\Users\\HP\\data\\1136591.yaml', 'C:\\Users\\HP\\data\\1136592.yaml', 'C:\\Users\\HP\\data\\1136593.yaml', 'C:\\Users\\HP\\data\\1136594.yaml', 'C:\\Users\\HP\\data\\1136595.yaml', 'C:\\Users\\HP\\data\\1136596.yaml', 'C:\\Users\\HP\\data\\1136597.yaml', 'C:\\Users\\HP\\data\\1136598.yaml', 'C:\\Users\\HP\\data\\1136599.yaml', 'C:\\Users\\HP\\data\\1136600.yaml', 'C:\\Users\\HP\\data\\1136601.yaml', 'C:\\Users\\HP\\data\\1136602.yaml', 'C:\\Users\\HP\\data\\1136603.yaml', 'C:\\Users\\HP\\data\\1136604.yaml', 'C:\\Users\\HP\\data\\1136605.yaml', 'C:\\Users\\HP\\data\\1136606.yaml', 'C:\\Users\\HP\\data\\1136607.yaml', 'C:\\Users\\HP\\data\\1136608.yaml', 'C:\\Users\\HP\\data\\1136609.yaml', 'C:\\Users\\HP\\data\\1136610.yaml', 'C:\\Users\\HP\\data\\1136611.yaml', 'C:\\Users\\HP\\data\\1136612.yaml', 'C:\\Users\\HP\\data\\1136613.yaml', 'C:\\Users\\HP\\data\\1136614.yaml', 'C:\\Users\\HP\\data\\1136615.yaml', 'C:\\Users\\HP\\data\\1136616.yaml', 'C:\\Users\\HP\\data\\1136617.yaml', 'C:\\Users\\HP\\data\\1136618.yaml', 'C:\\Users\\HP\\data\\1136619.yaml', 'C:\\Users\\HP\\data\\1136620.yaml', 'C:\\Users\\HP\\data\\1175356.yaml', 'C:\\Users\\HP\\data\\1175357.yaml', 'C:\\Users\\HP\\data\\1175358.yaml', 'C:\\Users\\HP\\data\\1175359.yaml', 'C:\\Users\\HP\\data\\1175360.yaml', 'C:\\Users\\HP\\data\\1175361.yaml', 'C:\\Users\\HP\\data\\1175362.yaml', 'C:\\Users\\HP\\data\\1175363.yaml', 'C:\\Users\\HP\\data\\1175364.yaml', 'C:\\Users\\HP\\data\\1175365.yaml', 'C:\\Users\\HP\\data\\1175366.yaml', 'C:\\Users\\HP\\data\\1175367.yaml', 'C:\\Users\\HP\\data\\1175368.yaml', 'C:\\Users\\HP\\data\\1175369.yaml', 'C:\\Users\\HP\\data\\1175370.yaml', 'C:\\Users\\HP\\data\\1175371.yaml', 'C:\\Users\\HP\\data\\1175372.yaml', 'C:\\Users\\HP\\data\\1178393.yaml', 'C:\\Users\\HP\\data\\1178394.yaml', 'C:\\Users\\HP\\data\\1178395.yaml', 'C:\\Users\\HP\\data\\1178396.yaml', 'C:\\Users\\HP\\data\\1178397.yaml', 'C:\\Users\\HP\\data\\1178398.yaml', 'C:\\Users\\HP\\data\\1178399.yaml', 'C:\\Users\\HP\\data\\1178400.yaml', 'C:\\Users\\HP\\data\\1178401.yaml', 'C:\\Users\\HP\\data\\1178402.yaml', 'C:\\Users\\HP\\data\\1178403.yaml', 'C:\\Users\\HP\\data\\1178404.yaml', 'C:\\Users\\HP\\data\\1178405.yaml', 'C:\\Users\\HP\\data\\1178406.yaml', 'C:\\Users\\HP\\data\\1178407.yaml', 'C:\\Users\\HP\\data\\1178408.yaml', 'C:\\Users\\HP\\data\\1178409.yaml', 'C:\\Users\\HP\\data\\1178410.yaml', 'C:\\Users\\HP\\data\\1178411.yaml', 'C:\\Users\\HP\\data\\1178412.yaml', 'C:\\Users\\HP\\data\\1178413.yaml', 'C:\\Users\\HP\\data\\1178414.yaml', 'C:\\Users\\HP\\data\\1178415.yaml', 'C:\\Users\\HP\\data\\1178416.yaml', 'C:\\Users\\HP\\data\\1178417.yaml', 'C:\\Users\\HP\\data\\1178418.yaml', 'C:\\Users\\HP\\data\\1178419.yaml', 'C:\\Users\\HP\\data\\1178420.yaml', 'C:\\Users\\HP\\data\\1178421.yaml', 'C:\\Users\\HP\\data\\1178422.yaml', 'C:\\Users\\HP\\data\\1178423.yaml', 'C:\\Users\\HP\\data\\1178424.yaml', 'C:\\Users\\HP\\data\\1178425.yaml', 'C:\\Users\\HP\\data\\1178426.yaml', 'C:\\Users\\HP\\data\\1178427.yaml', 'C:\\Users\\HP\\data\\1178428.yaml', 'C:\\Users\\HP\\data\\1178429.yaml', 'C:\\Users\\HP\\data\\1178430.yaml', 'C:\\Users\\HP\\data\\1178431.yaml', 'C:\\Users\\HP\\data\\1181764.yaml', 'C:\\Users\\HP\\data\\1181766.yaml', 'C:\\Users\\HP\\data\\1181767.yaml', 'C:\\Users\\HP\\data\\1181768.yaml', 'C:\\Users\\HP\\data\\1216492.yaml', 'C:\\Users\\HP\\data\\1216493.yaml', 'C:\\Users\\HP\\data\\1216494.yaml', 'C:\\Users\\HP\\data\\1216495.yaml', 'C:\\Users\\HP\\data\\1216496.yaml', 'C:\\Users\\HP\\data\\1216497.yaml', 'C:\\Users\\HP\\data\\1216498.yaml', 'C:\\Users\\HP\\data\\1216499.yaml', 'C:\\Users\\HP\\data\\1216500.yaml', 'C:\\Users\\HP\\data\\1216501.yaml', 'C:\\Users\\HP\\data\\1216502.yaml', 'C:\\Users\\HP\\data\\1216503.yaml', 'C:\\Users\\HP\\data\\1216504.yaml', 'C:\\Users\\HP\\data\\1216505.yaml', 'C:\\Users\\HP\\data\\1216506.yaml', 'C:\\Users\\HP\\data\\1216507.yaml', 'C:\\Users\\HP\\data\\1216508.yaml', 'C:\\Users\\HP\\data\\1216509.yaml', 'C:\\Users\\HP\\data\\1216510.yaml', 'C:\\Users\\HP\\data\\1216511.yaml', 'C:\\Users\\HP\\data\\1216512.yaml', 'C:\\Users\\HP\\data\\1216513.yaml', 'C:\\Users\\HP\\data\\1216514.yaml', 'C:\\Users\\HP\\data\\1216515.yaml', 'C:\\Users\\HP\\data\\1216516.yaml', 'C:\\Users\\HP\\data\\1216517.yaml', 'C:\\Users\\HP\\data\\1216518.yaml', 'C:\\Users\\HP\\data\\1216519.yaml', 'C:\\Users\\HP\\data\\1216520.yaml', 'C:\\Users\\HP\\data\\1216521.yaml', 'C:\\Users\\HP\\data\\1216522.yaml', 'C:\\Users\\HP\\data\\1216523.yaml', 'C:\\Users\\HP\\data\\1216524.yaml', 'C:\\Users\\HP\\data\\1216525.yaml', 'C:\\Users\\HP\\data\\1216526.yaml', 'C:\\Users\\HP\\data\\1216527.yaml', 'C:\\Users\\HP\\data\\1216528.yaml', 'C:\\Users\\HP\\data\\1216529.yaml', 'C:\\Users\\HP\\data\\1216530.yaml', 'C:\\Users\\HP\\data\\1216531.yaml', 'C:\\Users\\HP\\data\\1216532.yaml', 'C:\\Users\\HP\\data\\1216533.yaml', 'C:\\Users\\HP\\data\\1216534.yaml', 'C:\\Users\\HP\\data\\1216535.yaml', 'C:\\Users\\HP\\data\\1216536.yaml', 'C:\\Users\\HP\\data\\1216537.yaml', 'C:\\Users\\HP\\data\\1216538.yaml', 'C:\\Users\\HP\\data\\1216539.yaml', 'C:\\Users\\HP\\data\\1216540.yaml', 'C:\\Users\\HP\\data\\1216541.yaml', 'C:\\Users\\HP\\data\\1216542.yaml', 'C:\\Users\\HP\\data\\1216543.yaml', 'C:\\Users\\HP\\data\\1216544.yaml', 'C:\\Users\\HP\\data\\1216545.yaml', 'C:\\Users\\HP\\data\\1216546.yaml', 'C:\\Users\\HP\\data\\1216547.yaml', 'C:\\Users\\HP\\data\\1237177.yaml', 'C:\\Users\\HP\\data\\1237178.yaml', 'C:\\Users\\HP\\data\\1237180.yaml', 'C:\\Users\\HP\\data\\1237181.yaml', 'C:\\Users\\HP\\data\\1254058.yaml', 'C:\\Users\\HP\\data\\1254059.yaml', 'C:\\Users\\HP\\data\\1254060.yaml', 'C:\\Users\\HP\\data\\1254061.yaml', 'C:\\Users\\HP\\data\\1254062.yaml', 'C:\\Users\\HP\\data\\1254063.yaml', 'C:\\Users\\HP\\data\\1254064.yaml', 'C:\\Users\\HP\\data\\1254065.yaml', 'C:\\Users\\HP\\data\\1254066.yaml', 'C:\\Users\\HP\\data\\1254067.yaml', 'C:\\Users\\HP\\data\\1254068.yaml', 'C:\\Users\\HP\\data\\1254069.yaml', 'C:\\Users\\HP\\data\\1254070.yaml', 'C:\\Users\\HP\\data\\1254071.yaml', 'C:\\Users\\HP\\data\\1254072.yaml', 'C:\\Users\\HP\\data\\1254073.yaml', 'C:\\Users\\HP\\data\\1254074.yaml', 'C:\\Users\\HP\\data\\1254075.yaml', 'C:\\Users\\HP\\data\\1254076.yaml', 'C:\\Users\\HP\\data\\1254077.yaml', 'C:\\Users\\HP\\data\\1254078.yaml', 'C:\\Users\\HP\\data\\1254079.yaml', 'C:\\Users\\HP\\data\\1254080.yaml', 'C:\\Users\\HP\\data\\1254081.yaml', 'C:\\Users\\HP\\data\\1254082.yaml', 'C:\\Users\\HP\\data\\1254083.yaml', 'C:\\Users\\HP\\data\\1254084.yaml', 'C:\\Users\\HP\\data\\1254085.yaml', 'C:\\Users\\HP\\data\\1254086.yaml', 'C:\\Users\\HP\\data\\1254087.yaml', 'C:\\Users\\HP\\data\\1254088.yaml', 'C:\\Users\\HP\\data\\1254089.yaml', 'C:\\Users\\HP\\data\\1254090.yaml', 'C:\\Users\\HP\\data\\1254091.yaml', 'C:\\Users\\HP\\data\\1254092.yaml', 'C:\\Users\\HP\\data\\1254093.yaml', 'C:\\Users\\HP\\data\\1254094.yaml', 'C:\\Users\\HP\\data\\1254095.yaml', 'C:\\Users\\HP\\data\\1254096.yaml', 'C:\\Users\\HP\\data\\1254097.yaml', 'C:\\Users\\HP\\data\\1254098.yaml', 'C:\\Users\\HP\\data\\1254099.yaml', 'C:\\Users\\HP\\data\\1254100.yaml', 'C:\\Users\\HP\\data\\1254101.yaml', 'C:\\Users\\HP\\data\\1254102.yaml', 'C:\\Users\\HP\\data\\1254103.yaml', 'C:\\Users\\HP\\data\\1254104.yaml', 'C:\\Users\\HP\\data\\1254105.yaml', 'C:\\Users\\HP\\data\\1254106.yaml', 'C:\\Users\\HP\\data\\1254107.yaml', 'C:\\Users\\HP\\data\\1254108.yaml', 'C:\\Users\\HP\\data\\1254109.yaml', 'C:\\Users\\HP\\data\\1254110.yaml', 'C:\\Users\\HP\\data\\1254111.yaml', 'C:\\Users\\HP\\data\\1254112.yaml', 'C:\\Users\\HP\\data\\1254113.yaml', 'C:\\Users\\HP\\data\\1254114.yaml', 'C:\\Users\\HP\\data\\1254115.yaml', 'C:\\Users\\HP\\data\\1254116.yaml', 'C:\\Users\\HP\\data\\1254117.yaml', 'C:\\Users\\HP\\data\\1304047.yaml', 'C:\\Users\\HP\\data\\1304048.yaml', 'C:\\Users\\HP\\data\\1304049.yaml', 'C:\\Users\\HP\\data\\1304050.yaml', 'C:\\Users\\HP\\data\\1304051.yaml', 'C:\\Users\\HP\\data\\1304052.yaml', 'C:\\Users\\HP\\data\\1304053.yaml', 'C:\\Users\\HP\\data\\1304054.yaml', 'C:\\Users\\HP\\data\\1304055.yaml', 'C:\\Users\\HP\\data\\1304056.yaml', 'C:\\Users\\HP\\data\\1304057.yaml', 'C:\\Users\\HP\\data\\1304058.yaml', 'C:\\Users\\HP\\data\\1304059.yaml', 'C:\\Users\\HP\\data\\1304060.yaml', 'C:\\Users\\HP\\data\\1304061.yaml', 'C:\\Users\\HP\\data\\1304062.yaml', 'C:\\Users\\HP\\data\\1304063.yaml', 'C:\\Users\\HP\\data\\1304064.yaml', 'C:\\Users\\HP\\data\\1304065.yaml', 'C:\\Users\\HP\\data\\1304066.yaml', 'C:\\Users\\HP\\data\\1304067.yaml', 'C:\\Users\\HP\\data\\1304068.yaml', 'C:\\Users\\HP\\data\\1304069.yaml', 'C:\\Users\\HP\\data\\1304070.yaml', 'C:\\Users\\HP\\data\\1304071.yaml', 'C:\\Users\\HP\\data\\1304072.yaml', 'C:\\Users\\HP\\data\\1304073.yaml', 'C:\\Users\\HP\\data\\1304074.yaml', 'C:\\Users\\HP\\data\\1304075.yaml', 'C:\\Users\\HP\\data\\1304076.yaml', 'C:\\Users\\HP\\data\\1304077.yaml', 'C:\\Users\\HP\\data\\1304078.yaml', 'C:\\Users\\HP\\data\\1304079.yaml', 'C:\\Users\\HP\\data\\1304080.yaml', 'C:\\Users\\HP\\data\\1304081.yaml', 'C:\\Users\\HP\\data\\1304082.yaml', 'C:\\Users\\HP\\data\\1304083.yaml', 'C:\\Users\\HP\\data\\1304084.yaml', 'C:\\Users\\HP\\data\\1304085.yaml', 'C:\\Users\\HP\\data\\1304086.yaml', 'C:\\Users\\HP\\data\\1304087.yaml', 'C:\\Users\\HP\\data\\1304088.yaml', 'C:\\Users\\HP\\data\\1304089.yaml', 'C:\\Users\\HP\\data\\1304090.yaml', 'C:\\Users\\HP\\data\\1304091.yaml', 'C:\\Users\\HP\\data\\1304092.yaml', 'C:\\Users\\HP\\data\\1304093.yaml', 'C:\\Users\\HP\\data\\1304094.yaml', 'C:\\Users\\HP\\data\\1304095.yaml', 'C:\\Users\\HP\\data\\1304096.yaml', 'C:\\Users\\HP\\data\\1304097.yaml', 'C:\\Users\\HP\\data\\1304098.yaml', 'C:\\Users\\HP\\data\\1304099.yaml', 'C:\\Users\\HP\\data\\1304100.yaml', 'C:\\Users\\HP\\data\\1304101.yaml', 'C:\\Users\\HP\\data\\1304102.yaml', 'C:\\Users\\HP\\data\\1304103.yaml', 'C:\\Users\\HP\\data\\1304104.yaml', 'C:\\Users\\HP\\data\\1304105.yaml', 'C:\\Users\\HP\\data\\1304106.yaml', 'C:\\Users\\HP\\data\\1304107.yaml', 'C:\\Users\\HP\\data\\1304108.yaml', 'C:\\Users\\HP\\data\\1304109.yaml', 'C:\\Users\\HP\\data\\1304110.yaml', 'C:\\Users\\HP\\data\\1304111.yaml', 'C:\\Users\\HP\\data\\1304112.yaml', 'C:\\Users\\HP\\data\\1304113.yaml', 'C:\\Users\\HP\\data\\1304114.yaml', 'C:\\Users\\HP\\data\\1304115.yaml', 'C:\\Users\\HP\\data\\1304116.yaml', 'C:\\Users\\HP\\data\\1312197.yaml', 'C:\\Users\\HP\\data\\1312198.yaml', 'C:\\Users\\HP\\data\\1312199.yaml', 'C:\\Users\\HP\\data\\1312200.yaml', 'C:\\Users\\HP\\data\\1359475.yaml', 'C:\\Users\\HP\\data\\1359476.yaml', 'C:\\Users\\HP\\data\\1359477.yaml', 'C:\\Users\\HP\\data\\1359478.yaml', 'C:\\Users\\HP\\data\\1359479.yaml', 'C:\\Users\\HP\\data\\1359480.yaml', 'C:\\Users\\HP\\data\\1359481.yaml', 'C:\\Users\\HP\\data\\1359482.yaml', 'C:\\Users\\HP\\data\\1359483.yaml', 'C:\\Users\\HP\\data\\1359484.yaml', 'C:\\Users\\HP\\data\\1359485.yaml', 'C:\\Users\\HP\\data\\1359486.yaml', 'C:\\Users\\HP\\data\\1359487.yaml', 'C:\\Users\\HP\\data\\1359488.yaml', 'C:\\Users\\HP\\data\\1359489.yaml', 'C:\\Users\\HP\\data\\1359490.yaml', 'C:\\Users\\HP\\data\\1359491.yaml', 'C:\\Users\\HP\\data\\1359492.yaml', 'C:\\Users\\HP\\data\\1359493.yaml', 'C:\\Users\\HP\\data\\1359494.yaml', 'C:\\Users\\HP\\data\\1359495.yaml', 'C:\\Users\\HP\\data\\1359496.yaml', 'C:\\Users\\HP\\data\\1359497.yaml', 'C:\\Users\\HP\\data\\1359498.yaml', 'C:\\Users\\HP\\data\\1359499.yaml', 'C:\\Users\\HP\\data\\1359500.yaml', 'C:\\Users\\HP\\data\\1359501.yaml', 'C:\\Users\\HP\\data\\1359502.yaml', 'C:\\Users\\HP\\data\\1359503.yaml', 'C:\\Users\\HP\\data\\1359504.yaml', 'C:\\Users\\HP\\data\\1359505.yaml', 'C:\\Users\\HP\\data\\1359506.yaml', 'C:\\Users\\HP\\data\\1359507.yaml', 'C:\\Users\\HP\\data\\1359508.yaml', 'C:\\Users\\HP\\data\\1359509.yaml', 'C:\\Users\\HP\\data\\1359510.yaml', 'C:\\Users\\HP\\data\\1359511.yaml', 'C:\\Users\\HP\\data\\1359512.yaml', 'C:\\Users\\HP\\data\\1359513.yaml', 'C:\\Users\\HP\\data\\1359514.yaml', 'C:\\Users\\HP\\data\\1359515.yaml', 'C:\\Users\\HP\\data\\1359516.yaml', 'C:\\Users\\HP\\data\\1359517.yaml', 'C:\\Users\\HP\\data\\1359518.yaml', 'C:\\Users\\HP\\data\\1359519.yaml', 'C:\\Users\\HP\\data\\1359520.yaml', 'C:\\Users\\HP\\data\\1359521.yaml', 'C:\\Users\\HP\\data\\1359522.yaml', 'C:\\Users\\HP\\data\\1359523.yaml', 'C:\\Users\\HP\\data\\1359524.yaml', 'C:\\Users\\HP\\data\\1359525.yaml', 'C:\\Users\\HP\\data\\1359526.yaml', 'C:\\Users\\HP\\data\\1359527.yaml', 'C:\\Users\\HP\\data\\1359528.yaml', 'C:\\Users\\HP\\data\\1359529.yaml', 'C:\\Users\\HP\\data\\1359530.yaml', 'C:\\Users\\HP\\data\\1359531.yaml', 'C:\\Users\\HP\\data\\1359532.yaml', 'C:\\Users\\HP\\data\\1359533.yaml', 'C:\\Users\\HP\\data\\1359534.yaml', 'C:\\Users\\HP\\data\\1359535.yaml', 'C:\\Users\\HP\\data\\1359536.yaml', 'C:\\Users\\HP\\data\\1359537.yaml', 'C:\\Users\\HP\\data\\1359538.yaml', 'C:\\Users\\HP\\data\\1359539.yaml', 'C:\\Users\\HP\\data\\1359540.yaml', 'C:\\Users\\HP\\data\\1359541.yaml', 'C:\\Users\\HP\\data\\1359542.yaml', 'C:\\Users\\HP\\data\\1359543.yaml', 'C:\\Users\\HP\\data\\1359544.yaml', 'C:\\Users\\HP\\data\\1370350.yaml', 'C:\\Users\\HP\\data\\1370351.yaml', 'C:\\Users\\HP\\data\\1370352.yaml', 'C:\\Users\\HP\\data\\1370353.yaml', 'C:\\Users\\HP\\data\\1422119.yaml', 'C:\\Users\\HP\\data\\1422120.yaml', 'C:\\Users\\HP\\data\\1422121.yaml', 'C:\\Users\\HP\\data\\1422122.yaml', 'C:\\Users\\HP\\data\\1422123.yaml', 'C:\\Users\\HP\\data\\1422124.yaml', 'C:\\Users\\HP\\data\\1422125.yaml', 'C:\\Users\\HP\\data\\1422126.yaml', 'C:\\Users\\HP\\data\\1422127.yaml', 'C:\\Users\\HP\\data\\1422128.yaml', 'C:\\Users\\HP\\data\\1422129.yaml', 'C:\\Users\\HP\\data\\1422130.yaml', 'C:\\Users\\HP\\data\\1422131.yaml', 'C:\\Users\\HP\\data\\1422132.yaml', 'C:\\Users\\HP\\data\\1422133.yaml', 'C:\\Users\\HP\\data\\1422134.yaml', 'C:\\Users\\HP\\data\\1422135.yaml', 'C:\\Users\\HP\\data\\1422136.yaml', 'C:\\Users\\HP\\data\\1422137.yaml', 'C:\\Users\\HP\\data\\1422138.yaml', 'C:\\Users\\HP\\data\\1422139.yaml', 'C:\\Users\\HP\\data\\1426260.yaml', 'C:\\Users\\HP\\data\\1426261.yaml', 'C:\\Users\\HP\\data\\1426262.yaml', 'C:\\Users\\HP\\data\\1426263.yaml', 'C:\\Users\\HP\\data\\1426264.yaml', 'C:\\Users\\HP\\data\\1426265.yaml', 'C:\\Users\\HP\\data\\1426266.yaml', 'C:\\Users\\HP\\data\\1426267.yaml', 'C:\\Users\\HP\\data\\1426268.yaml', 'C:\\Users\\HP\\data\\1426269.yaml', 'C:\\Users\\HP\\data\\1426270.yaml', 'C:\\Users\\HP\\data\\1426271.yaml', 'C:\\Users\\HP\\data\\1426272.yaml', 'C:\\Users\\HP\\data\\1426273.yaml', 'C:\\Users\\HP\\data\\1426274.yaml', 'C:\\Users\\HP\\data\\1426275.yaml', 'C:\\Users\\HP\\data\\1426276.yaml', 'C:\\Users\\HP\\data\\1426277.yaml', 'C:\\Users\\HP\\data\\1426278.yaml', 'C:\\Users\\HP\\data\\1426279.yaml', 'C:\\Users\\HP\\data\\1426280.yaml', 'C:\\Users\\HP\\data\\1426281.yaml', 'C:\\Users\\HP\\data\\1426282.yaml', 'C:\\Users\\HP\\data\\1426283.yaml', 'C:\\Users\\HP\\data\\1426284.yaml', 'C:\\Users\\HP\\data\\1426285.yaml', 'C:\\Users\\HP\\data\\1426286.yaml', 'C:\\Users\\HP\\data\\1426287.yaml', 'C:\\Users\\HP\\data\\1426288.yaml', 'C:\\Users\\HP\\data\\1426289.yaml', 'C:\\Users\\HP\\data\\1426290.yaml', 'C:\\Users\\HP\\data\\1426291.yaml', 'C:\\Users\\HP\\data\\1426292.yaml', 'C:\\Users\\HP\\data\\1426293.yaml', 'C:\\Users\\HP\\data\\1426294.yaml', 'C:\\Users\\HP\\data\\1426295.yaml', 'C:\\Users\\HP\\data\\1426296.yaml', 'C:\\Users\\HP\\data\\1426297.yaml', 'C:\\Users\\HP\\data\\1426298.yaml', 'C:\\Users\\HP\\data\\1426299.yaml', 'C:\\Users\\HP\\data\\1426300.yaml', 'C:\\Users\\HP\\data\\1426302.yaml', 'C:\\Users\\HP\\data\\1426303.yaml', 'C:\\Users\\HP\\data\\1426305.yaml', 'C:\\Users\\HP\\data\\1426306.yaml', 'C:\\Users\\HP\\data\\1426307.yaml', 'C:\\Users\\HP\\data\\1426309.yaml', 'C:\\Users\\HP\\data\\1426310.yaml', 'C:\\Users\\HP\\data\\1426311.yaml', 'C:\\Users\\HP\\data\\1426312.yaml', 'C:\\Users\\HP\\data\\335982.yaml', 'C:\\Users\\HP\\data\\335983.yaml', 'C:\\Users\\HP\\data\\335984.yaml', 'C:\\Users\\HP\\data\\335985.yaml', 'C:\\Users\\HP\\data\\335986.yaml', 'C:\\Users\\HP\\data\\335987.yaml', 'C:\\Users\\HP\\data\\335988.yaml', 'C:\\Users\\HP\\data\\335989.yaml', 'C:\\Users\\HP\\data\\335990.yaml', 'C:\\Users\\HP\\data\\335991.yaml', 'C:\\Users\\HP\\data\\335992.yaml', 'C:\\Users\\HP\\data\\335993.yaml', 'C:\\Users\\HP\\data\\335994.yaml', 'C:\\Users\\HP\\data\\335995.yaml', 'C:\\Users\\HP\\data\\335996.yaml', 'C:\\Users\\HP\\data\\335997.yaml', 'C:\\Users\\HP\\data\\335998.yaml', 'C:\\Users\\HP\\data\\335999.yaml', 'C:\\Users\\HP\\data\\336000.yaml', 'C:\\Users\\HP\\data\\336001.yaml', 'C:\\Users\\HP\\data\\336002.yaml', 'C:\\Users\\HP\\data\\336003.yaml'

In [67]:
import numpy as np
import pandas as pd
from yaml import safe_load
# import os
# from tqdm import tqdm

In [69]:
import os
print(os.getcwd())  # This prints the current working directory

c:\Users\HP\data

In [70]:
filenames[0:5]

['C:\\Users\\HP\\data\\.ipynb_checkpoints',
 'C:\\Users\\HP\\data\\1082591.yaml',
 'C:\\Users\\HP\\data\\1082592.yaml',
 'C:\\Users\\HP\\data\\1082593.yaml',
 'C:\\Users\\HP\\data\\1082594.yaml']

In [17]:
import os
import pandas as pd
from tqdm import tqdm
from yaml import safe_load

# Folder path
folder_path = r'C:\Users\HP\data'

# Get list of valid files (ignoring .ipynb_checkpoints and directories)
filenames = [os.path.join(folder_path, file) for file in os.listdir(folder_path) 
             if not file.startswith('.ipynb_checkpoints') and os.path.isfile(os.path.join(folder_path, file))]

final_data = []  # Use a list instead of appending DataFrames directly
counter = 1

for file in tqdm(filenames, desc="Processing Files"):
    try:
        with open(file, 'r') as f:
            data = safe_load(f)  # Load YAML/JSON data
            
            if data:  # Check if data is not empty
                df = pd.json_normalize(data)  # Convert to DataFrame
                df['match_id'] = counter  # Add match_id
                final_data.append(df)  # Store DataFrame in list
                counter += 1
    except PermissionError:
        print(f"Skipping file due to permission error: {file}")
    except Exception as e:
        print(f"Error processing {file}: {e}")

# Create a single DataFrame after the loop
final_df = pd.concat(final_data, ignore_index=True) if final_data else pd.DataFrame()

# Display final DataFrame shape
print(f"Final DataFrame shape: {final_df.shape}")

Processing Files: 100%|███████████████████████████████████████████████████████████▊| 1099/1102 [03:59<00:00,  9.39it/s]

Error processing C:\Users\HP\data\dataset_level1.pk11: 'charmap' codec can't decode byte 0x81 in position 46: character maps to <undefined>
Error processing C:\Users\HP\data\dataset_level1.pkl: 'charmap' codec can't decode byte 0x81 in position 46: character maps to <undefined>
Error processing C:\Users\HP\data\dataset_level2.pkl: 'charmap' codec can't decode byte 0x81 in position 46: character maps to <undefined>
Error processing C:\Users\HP\data\README.txt:

Processing Files: 100%|████████████████████████████████████████████████████████████| 1102/1102 [04:00<00:00,  4.58it/s]

Final DataFrame shape: (1098, 941)

In [3]:
import pickle
import numpy as np
import pandas as pd

# Save the DataFrame to a pickle file
pickle.dump(final_df, open('dataset_level1.pkl', 'wb'))

NameError: name 'final_df' is not defined

In [4]:
backup = final_df.copy()

NameError: name 'final_df' is not defined

In [26]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.competition,info.dates,info.gender,info.match_type,...,metadata.kernelspec.language,metadata.kernelspec.name,metadata.language_info.codemirror_mode.name,metadata.language_info.codemirror_mode.version,metadata.language_info.file_extension,metadata.language_info.mimetype,metadata.language_info.name,metadata.language_info.nbconvert_exporter,metadata.language_info.pygments_lexer,metadata.language_info.version
0,[{'1st innings': {'team': 'Sunrisers Hyderabad...,0.91,2017-04-06,1.0,6.0,Hyderabad,IPL,[2017-04-05],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Mumbai Indians', 'd...",0.91,2017-04-07,1.0,6.0,Pune,IPL,[2017-04-06],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Gujarat Lions', 'de...",0.91,2017-04-07,2.0,6.0,Rajkot,IPL,[2017-04-07],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[{'1st innings': {'team': 'Rising Pune Supergi...,0.91,2017-04-08,1.0,6.0,Indore,IPL,[2017-04-08],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[{'1st innings': {'team': 'Royal Challengers B...,0.91,2017-04-08,2.0,6.0,Bengaluru,IPL,[2017-04-08],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,"[{'1st innings': {'team': 'Gujarat Lions', 'de...",0.91,2016-05-28,1.0,6.0,Delhi,IPL,[2016-05-27],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1094,[{'1st innings': {'team': 'Sunrisers Hyderabad...,0.91,2016-05-30,1.0,6.0,Bangalore,IPL,[2016-05-29],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,python,python3,ipython,3.0,.py,text/x-python,python,python,ipython3,3.13.0
1096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,python,python3,ipython,3.0,.py,text/x-python,python,python,ipython3,3.13.0
1097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,python,python3,ipython,3.0,.py,text/x-python,python,python,ipython3,3.13.0

In [46]:
print(final_df.columns.tolist())

['innings', 'meta.data_version', 'meta.created', 'meta.revision', 'info.balls_per_over', 'info.city', 'info.competition', 'info.dates', 'info.gender', 'info.match_type', 'info.outcome.by.runs', 'info.outcome.winner', 'info.overs', 'info.player_of_match', 'info.players.Royal Challengers Bangalore', 'info.players.Sunrisers Hyderabad', 'info.players.Mumbai Indians', 'info.players.Rising Pune Supergiant', 'info.players.Gujarat Lions', 'info.players.Kolkata Knight Riders', 'info.players.Kings XI Punjab', 'info.players.Delhi Daredevils', 'info.players.Chennai Super Kings', 'info.players.Rajasthan Royals', 'info.players.Delhi Capitals', 'info.players.Punjab Kings', 'info.players.Lucknow Super Giants', 'info.players.Gujarat Titans', 'info.players.Royal Challengers Bengaluru', 'info.players.Deccan Chargers', 'info.players.Kochi Tuskers Kerala', 'info.players.Pune Warriors', 'info.players.Rising Pune Supergiants', 'player1', 'player2', 'player3', 'player4', 'player5', 'player6', 'player7', 'player8', 'player9', 'player10', 'player11', 'player12', 'player13', 'player14', 'player15', 'player16', 'player17', 'player18', 'player19', 'player20', 'player21', 'player22', 'player23', 'player24', 'player25', 'first_date']

In [47]:
import ast  # if you need to convert string lists to real lists

# Step 1: find all team player columns
player_cols = [col for col in final_df.columns if col.startswith('info.players.')]

teams_players = {}

for col in player_cols:
    # Step 2: get team name by removing prefix
    team_name = col.replace('info.players.', '')
    
    # Step 3: get players from the first row (adjust index if multiple rows)
    players = final_df.loc[0, col]
    
    # If players are strings that look like lists, convert them
    if isinstance(players, str):
        try:
            players = ast.literal_eval(players)
        except:
            pass  # if it’s not a string representation of list, just keep it
    
    teams_players[team_name] = players

# Now teams_players is a dictionary: { team_name: [players_list] }

# Example: print each team and its players
for team, players in teams_players.items():
    print(f"Team: {team}")
    print("Players:", players)
    print()

Team: Royal Challengers Bangalore
Players: ['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind', 'TS Mills', 'YS Chahal', 'A Choudhary']

Team: Sunrisers Hyderabad
Players: ['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh', 'DJ Hooda', 'BCJ Cutting', 'NV Ojha', 'Bipul Sharma', 'B Kumar', 'A Nehra', 'Rashid Khan']

Team: Mumbai Indians
Players: nan

Team: Rising Pune Supergiant
Players: nan

Team: Gujarat Lions
Players: nan

Team: Kolkata Knight Riders
Players: nan

Team: Kings XI Punjab
Players: nan

Team: Delhi Daredevils
Players: nan

Team: Chennai Super Kings
Players: nan

Team: Rajasthan Royals
Players: nan

Team: Delhi Capitals
Players: nan

Team: Punjab Kings
Players: nan

Team: Lucknow Super Giants
Players: nan

Team: Gujarat Titans
Players: nan

Team: Royal Challengers Bengaluru
Players: nan

Team: Deccan Chargers
Players: nan

Team: Kochi Tuskers Kerala
Players: nan

Team: Pune Warriors
Players: nan

Team: Rising Pune Supergiants
Players: nan

In [49]:
# List of desired base columns
import ast

base_columns = [
    'innings', 'meta.data_version', 'meta.created', 'meta.revision',
    'info.balls_per_over', 'info.city', 'info.competition', 'info.dates',
    'info.gender', 'info.match_type', 'info.outcome.by.runs',
    'info.outcome.winner', 'info.overs', 'info.player_of_match'
]

# Keep only valid columns
valid_base_columns = [col for col in base_columns if col in final_df.columns]

# Get player columns dynamically
player_columns = [col for col in final_df.columns if col.startswith('info.players.')]

# Combine columns to keep in dataframe
columns_to_keep = valid_base_columns + player_columns

# Filter dataframe
final_df = final_df[columns_to_keep]

# Now flatten players into player1, player2, ... columns for each row
def extract_players(row):
    all_players = []
    for col in player_columns:
        players = row[col]
        if isinstance(players, str):
            try:
                players = ast.literal_eval(players)  # convert string list to list
            except:
                pass
        if isinstance(players, list):
            all_players.extend(players)
    return all_players

# Extract players per row
final_df['all_players'] = final_df.apply(extract_players, axis=1)

# Find max number of players in any row (to know how many columns needed)
max_players = final_df['all_players'].apply(len).max()

# Create separate player columns
for i in range(max_players):
    final_df[f'player{i+1}'] = final_df['all_players'].apply(lambda x: x[i] if i < len(x) else None)

# Drop the temporary combined column if you want
final_df.drop(columns=['all_players'], inplace=True)

print(final_df.head())

                                             innings  meta.data_version  \
0  [{'1st innings': {'team': 'Sunrisers Hyderabad...               0.91
1  [{'1st innings': {'team': 'Mumbai Indians', 'd...               0.91
2  [{'1st innings': {'team': 'Gujarat Lions', 'de...               0.91
3  [{'1st innings': {'team': 'Rising Pune Supergi...               0.91
4  [{'1st innings': {'team': 'Royal Challengers B...               0.91

  meta.created  meta.revision  info.balls_per_over  info.city  \
0   2017-04-06            1.0                  6.0  Hyderabad
1   2017-04-07            1.0                  6.0       Pune
2   2017-04-07            2.0                  6.0     Rajkot
3   2017-04-08            1.0                  6.0     Indore
4   2017-04-08            2.0                  6.0  Bengaluru

  info.competition    info.dates info.gender info.match_type  ...    player16  \
0              IPL  [2017-04-05]        male             T20  ...    DJ Hooda
1              IPL  [2017-04-06]        male             T20  ...    MS Dhoni
2              IPL  [2017-04-07]        male             T20  ...   YK Pathan
3              IPL  [2017-04-08]        male             T20  ...  GJ Maxwell
4              IPL  [2017-04-08]        male             T20  ...     RR Pant

      player17       player18       player19       player20        player21  \
0  BCJ Cutting        NV Ojha   Bipul Sharma        B Kumar         A Nehra
1    MK Tiwary       R Bhatia      DL Chahar        A Zampa        AB Dinda
2     SA Yadav      CR Woakes      PP Chawla  Kuldeep Yadav       SP Narine
3    DA Miller     MP Stoinis  Swapnil Singh      MM Sharma  Sandeep Sharma
4    CH Morris  CR Brathwaite     PJ Cummins       A Mishra        S Nadeem

      player22 player23 player24 player25
0  Rashid Khan     None     None     None
1  Imran Tahir     None     None     None
2     TA Boult     None     None     None
3  T Natarajan     None     None     None
4       Z Khan     None     None     None

[5 rows x 58 columns]

In [35]:
# player_columns = [col for col in matches.columns if col.startswith('info.players.')]
# print(player_columns)

In [50]:
import pandas as pd

# If 'info.dates' contains lists of date strings, extract the first date and convert to datetime
def extract_first_date(dates):
    if isinstance(dates, list) and len(dates) > 0:
        return pd.to_datetime(dates[0])
    else:
        # If already a string or datetime
        return pd.to_datetime(dates)

final_df['first_date'] = final_df['info.dates'].apply(extract_first_date)

# Now filter on the new datetime column
final_df = final_df[final_df['first_date'].dt.year >= 2017]

print(final_df.head())

                                             innings  meta.data_version  \
0  [{'1st innings': {'team': 'Sunrisers Hyderabad...               0.91
1  [{'1st innings': {'team': 'Mumbai Indians', 'd...               0.91
2  [{'1st innings': {'team': 'Gujarat Lions', 'de...               0.91
3  [{'1st innings': {'team': 'Rising Pune Supergi...               0.91
4  [{'1st innings': {'team': 'Royal Challengers B...               0.91

  meta.created  meta.revision  info.balls_per_over  info.city  \
0   2017-04-06            1.0                  6.0  Hyderabad
1   2017-04-07            1.0                  6.0       Pune
2   2017-04-07            2.0                  6.0     Rajkot
3   2017-04-08            1.0                  6.0     Indore
4   2017-04-08            2.0                  6.0  Bengaluru

  info.competition    info.dates info.gender info.match_type  ...  \
0              IPL  [2017-04-05]        male             T20  ...
1              IPL  [2017-04-06]        male             T20  ...
2              IPL  [2017-04-07]        male             T20  ...
3              IPL  [2017-04-08]        male             T20  ...
4              IPL  [2017-04-08]        male             T20  ...

      player17       player18       player19       player20        player21  \
0  BCJ Cutting        NV Ojha   Bipul Sharma        B Kumar         A Nehra
1    MK Tiwary       R Bhatia      DL Chahar        A Zampa        AB Dinda
2     SA Yadav      CR Woakes      PP Chawla  Kuldeep Yadav       SP Narine
3    DA Miller     MP Stoinis  Swapnil Singh      MM Sharma  Sandeep Sharma
4    CH Morris  CR Brathwaite     PJ Cummins       A Mishra        S Nadeem

      player22 player23 player24 player25 first_date
0  Rashid Khan     None     None     None 2017-04-05
1  Imran Tahir     None     None     None 2017-04-06
2     TA Boult     None     None     None 2017-04-07
3  T Natarajan     None     None     None 2017-04-08
4       Z Khan     None     None     None 2017-04-08

[5 rows x 59 columns]

In [52]:
print(final_df.columns.tolist())

['innings', 'meta.data_version', 'meta.created', 'meta.revision', 'info.balls_per_over', 'info.city', 'info.competition', 'info.dates', 'info.gender', 'info.match_type', 'info.outcome.by.runs', 'info.outcome.winner', 'info.overs', 'info.player_of_match', 'info.players.Royal Challengers Bangalore', 'info.players.Sunrisers Hyderabad', 'info.players.Mumbai Indians', 'info.players.Rising Pune Supergiant', 'info.players.Gujarat Lions', 'info.players.Kolkata Knight Riders', 'info.players.Kings XI Punjab', 'info.players.Delhi Daredevils', 'info.players.Chennai Super Kings', 'info.players.Rajasthan Royals', 'info.players.Delhi Capitals', 'info.players.Punjab Kings', 'info.players.Lucknow Super Giants', 'info.players.Gujarat Titans', 'info.players.Royal Challengers Bengaluru', 'info.players.Deccan Chargers', 'info.players.Kochi Tuskers Kerala', 'info.players.Pune Warriors', 'info.players.Rising Pune Supergiants', 'player1', 'player2', 'player3', 'player4', 'player5', 'player6', 'player7', 'player8', 'player9', 'player10', 'player11', 'player12', 'player13', 'player14', 'player15', 'player16', 'player17', 'player18', 'player19', 'player20', 'player21', 'player22', 'player23', 'player24', 'player25', 'first_date']

# RUN from HERE

In [5]:
import pickle
import numpy as np
import pandas as pd
pickle.dump(final_df,open('dataset_level1.pk11','wb'))
# pickle.dump(final_df,open('dataset_level1.pk01','wb'))

NameError: name 'final_df' is not defined

In [51]:
matches = pickle.load(open('dataset_level1.pk11','rb'))

matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'DA Warner',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.2: {'batsman': 'DA Warner',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'DA Warner',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {0.4: {'batsman': 'DA Warner',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.5: {'batsman': 'DA Warner',
   'bowler': 'TS Mills',
   'extras': {'wides': 2},
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 2, 'total': 2}}},
 {0.6: {'batsman': 'S Dhawan',
   'bowler': 'TS Mills',
   'non_striker': 'DA Warner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.7: {'batsman': 'S Dhawan',
   'bowler': 'TS Mills',
   'extras': {'legbyes': 1},
   'non_striker': 'DA Warner',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {1.1: {'batsman': 'S Dhawan',
   'bowler': 'A Choudhary',
   'non_striker': 'DA Warner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.2: {'batsman': 'DA Warner',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.3: {'batsman': 'DA Warner',
   'bowler': 'A Choudhary',
   'extras': {'noballs': 1},
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {1.4: {'batsman': 'DA Warner',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {1.5: {'batsman': 'DA Warner',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Mandeep Singh'],
    'kind': 'caught',
    'player_out': 'DA Warner'}}},
 {1.6: {'batsman': 'MC Henriques',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.7: {'batsman': 'MC Henriques',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.1: {'batsman': 'S Dhawan',
   'bowler': 'TS Mills',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.2: {'batsman': 'MC Henriques',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.3: {'batsman': 'MC Henriques',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.4: {'batsman': 'MC Henriques',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {2.5: {'batsman': 'S Dhawan',
   'bowler': 'TS Mills',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.6: {'batsman': 'MC Henriques',
   'bowler': 'TS Mills',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.1: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.3: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.4: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.5: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.6: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.1: {'batsman': 'S Dhawan',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.2: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.3: {'batsman': 'S Dhawan',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.4: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {4.5: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.6: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.1: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {5.2: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {5.3: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {5.5: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {5.6: {'batsman': 'S Dhawan',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.1: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.2: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.3: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.4: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.1: {'batsman': 'S Dhawan',
   'bowler': 'TM Head',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.2: {'batsman': 'MC Henriques',
   'bowler': 'TM Head',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'S Dhawan',
   'bowler': 'TM Head',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.4: {'batsman': 'MC Henriques',
   'bowler': 'TM Head',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {7.5: {'batsman': 'MC Henriques',
   'bowler': 'TM Head',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.6: {'batsman': 'S Dhawan',
   'bowler': 'TM Head',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.1: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {8.2: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.3: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'S Dhawan',
   'bowler': 'YS Chahal',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.5: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {8.6: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {9.1: {'batsman': 'S Dhawan',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.2: {'batsman': 'S Dhawan',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.3: {'batsman': 'MC Henriques',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.4: {'batsman': 'S Dhawan',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.5: {'batsman': 'MC Henriques',
   'bowler': 'A Choudhary',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.6: {'batsman': 'S Dhawan',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.1: {'batsman': 'MC Henriques',
   'bowler': 'STR Binny',
   'non_striker': 'S Dhawan',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.2: {'batsman': 'S Dhawan',
   'bowler': 'STR Binny',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {10.3: {'batsman': 'S Dhawan',
   'bowler': 'STR Binny',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Sachin Baby'],
    'kind': 'caught',
    'player_out': 'S Dhawan'}}},
 {10.4: {'batsman': 'MC Henriques',
   'bowler': 'STR Binny',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.5: {'batsman': 'Yuvraj Singh',
   'bowler': 'STR Binny',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {10.6: {'batsman': 'Yuvraj Singh',
   'bowler': 'STR Binny',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.1: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.2: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.4: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.5: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {11.6: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.1: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {12.2: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {12.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {12.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.5: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'extras': {'wides': 1},
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {12.6: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {12.7: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.1: {'batsman': 'Yuvraj Singh',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {13.2: {'batsman': 'Yuvraj Singh',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.3: {'batsman': 'MC Henriques',
   'bowler': 'SR Watson',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'SR Watson',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.5: {'batsman': 'MC Henriques',
   'bowler': 'SR Watson',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.6: {'batsman': 'MC Henriques',
   'bowler': 'SR Watson',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.1: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {14.2: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'S Aravind',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.5: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.6: {'batsman': 'MC Henriques',
   'bowler': 'S Aravind',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.1: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {15.2: {'batsman': 'MC Henriques',
   'bowler': 'YS Chahal',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Sachin Baby'],
    'kind': 'caught',
    'player_out': 'MC Henriques'}}},
 {15.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'YS Chahal',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.4: {'batsman': 'DJ Hooda',
   'bowler': 'YS Chahal',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.5: {'batsman': 'Yuvraj Singh',
   'bowler': 'YS Chahal',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.6: {'batsman': 'DJ Hooda',
   'bowler': 'YS Chahal',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.1: {'batsman': 'DJ Hooda',
   'bowler': 'TS Mills',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.2: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.5: {'batsman': 'DJ Hooda',
   'bowler': 'TS Mills',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.6: {'batsman': 'DJ Hooda',
   'bowler': 'TS Mills',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'DJ Hooda',
   'bowler': 'A Choudhary',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {17.2: {'batsman': 'DJ Hooda',
   'bowler': 'A Choudhary',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'extras': {'wides': 1},
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'extras': {'wides': 1},
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.5: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {17.6: {'batsman': 'Yuvraj Singh',
   'bowler': 'A Choudhary',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.7: {'batsman': 'DJ Hooda',
   'bowler': 'A Choudhary',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.8: {'batsman': 'DJ Hooda',
   'bowler': 'A Choudhary',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.1: {'batsman': 'DJ Hooda',
   'bowler': 'TS Mills',
   'non_striker': 'Yuvraj Singh',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.2: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {18.3: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {18.4: {'batsman': 'Yuvraj Singh',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'Yuvraj Singh'}}},
 {18.5: {'batsman': 'BCJ Cutting',
   'bowler': 'TS Mills',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.6: {'batsman': 'DJ Hooda',
   'bowler': 'TS Mills',
   'non_striker': 'BCJ Cutting',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.1: {'batsman': 'BCJ Cutting',
   'bowler': 'SR Watson',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.2: {'batsman': 'DJ Hooda',
   'bowler': 'SR Watson',
   'non_striker': 'BCJ Cutting',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.3: {'batsman': 'BCJ Cutting',
   'bowler': 'SR Watson',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {19.4: {'batsman': 'BCJ Cutting',
   'bowler': 'SR Watson',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.5: {'batsman': 'BCJ Cutting',
   'bowler': 'SR Watson',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.6: {'batsman': 'BCJ Cutting',
   'bowler': 'SR Watson',
   'non_striker': 'DJ Hooda',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}}]

In [52]:


print(matches['info.teams'].iloc[0])

['Sunrisers Hyderabad', 'Royal Challengers Bangalore']

In [53]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count += 1
        continue
    count += 1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
        'match_id': match_id,
        'teams': teams,
        'batting_team': batting_team,
        'ball': ball_of_match,
        'batsman': batsman,
        'bowler': bowler,
        'runs': runs,
        'player_dismissed': player_of_dismissed,
        'city': city,
        'venue': venue
    })
    
    # **Use pd.concat() instead of append()**
    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

In [54]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.1,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.2,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.3,DA Warner,TS Mills,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
3,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.4,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
4,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.5,DA Warner,TS Mills,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
...,...,...,...,...,...,...,...,...,...,...
63275,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.5,JD Unadkat,SP Narine,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63276,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.6,B Kumar,SP Narine,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63277,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.1,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63278,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.2,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63279,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.3,PJ Cummins,AD Russell,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"

In [55]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [56]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [57]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.1,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore
1,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.2,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore
2,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.3,DA Warner,TS Mills,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore
3,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.4,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore
4,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.5,DA Warner,TS Mills,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...
63275,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.5,JD Unadkat,SP Narine,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63276,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.6,B Kumar,SP Narine,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63277,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.1,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63278,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.2,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63279,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.3,PJ Cummins,AD Russell,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders

In [58]:
delivery_df.replace({
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Kings XI Punjab': 'Punjab Kings'
}, inplace=True)
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.1,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bengaluru
1,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.2,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bengaluru
2,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.3,DA Warner,TS Mills,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bengaluru
3,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.4,DA Warner,TS Mills,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bengaluru
4,2,"[Sunrisers Hyderabad, Royal Challengers Bangal...",Sunrisers Hyderabad,0.5,DA Warner,TS Mills,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bengaluru
...,...,...,...,...,...,...,...,...,...,...,...
63275,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.5,JD Unadkat,SP Narine,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63276,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,17.6,B Kumar,SP Narine,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63277,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.1,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63278,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.2,PJ Cummins,AD Russell,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders
63279,519,"[Sunrisers Hyderabad, Kolkata Knight Riders]",Sunrisers Hyderabad,18.3,PJ Cummins,AD Russell,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders

In [59]:
# delivery_df.drop(columns=['teams'],inplace=True)
delivery_df.shape

(63280, 11)

In [60]:
delivery_df['batting_team'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bengaluru',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Punjab Kings',
       'Rajasthan Royals', 'Chennai Super Kings', 'Delhi Capitals',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype=object)

In [61]:
teams = [
    'Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bengaluru',
       'Kolkata Knight Riders',  'Punjab Kings',
       'Rajasthan Royals', 'Chennai Super Kings', 'Delhi Capitals',   'Lucknow Super Giants', 'Gujarat Titans'
]

In [62]:
delivery_df['batting_team'].unique()
delivery_df.shape

(63280, 11)

In [63]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [64]:
delivery_df.shape

(56916, 11)

In [65]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [66]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.1,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.2,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.3,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.4,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.5,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
...,...,...,...,...,...,...,...,...
63275,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.5,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63276,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.6,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63277,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.1,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63278,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.2,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63279,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.3,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"

In [67]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [68]:
output[output['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium    3238
Sharjah Cricket Stadium                1493
Name: count, dtype: int64

In [69]:
output.loc[output['city'].isnull(), 'city'] = output['venue'].str.split().str[0]

In [70]:
output[output['city'].isnull()]['venue'].value_counts()

Series([], Name: count, dtype: int64)

In [71]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.1,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.2,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.3,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.4,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.5,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
...,...,...,...,...,...,...,...,...
63275,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.5,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63276,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.6,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63277,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.1,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63278,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.2,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"
63279,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.3,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai"

In [72]:
total_df = output.groupby('match_id').sum()['runs'].reset_index()
output = output.merge(total_df,on='match_id')

In [73]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,venue,runs_y
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.1,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.2,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.3,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.4,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.5,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207
...,...,...,...,...,...,...,...,...,...
56911,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.5,0,JD Unadkat,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113
56912,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.6,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113
56913,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.1,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113
56914,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.2,0,0,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113
56915,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.3,0,PJ Cummins,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113

In [258]:
# output['over'] = output['ball'].apply(lambda x:str(x).split(".")[0])
# output['ball_no'] = output['ball'].apply(lambda x:str(x).split(".")[1])

In [75]:
# Convert 'runs_x' column to numeric to avoid KeyError
if 'runs_x' in output.columns:
    output['runs_x'] = pd.to_numeric(output['runs_x'], errors='coerce')

# Calculate cumulative runs per match
output['current_runs'] = output.groupby('match_id')['runs_x'].cumsum()

# Extract 'over' and 'ball_no' from 'ball'
output['over'] = output['ball'].astype(str).str.split(".").str[0].astype(int)
output['ball_no'] = output['ball'].apply(lambda x: int(str(x).split(".")[1]) if "." in str(x) else 0)

# Compute 'balls_bowled' safely
output['balls_bowled'] = output['over'] * 6 + output['ball_no']

import pandas as pd
import numpy as np

# Ensure 'player_dismissed' is treated as a string first
output['player_dismissed'] = output['player_dismissed'].astype(str)

# Replace '0' with 0, and all other values with 1
output['player_dismissed'] = output['player_dismissed'].apply(lambda x: 0 if x == '0' else 1)

# Convert to integer safely
output['player_dismissed'] = pd.to_numeric(output['player_dismissed'], errors='coerce').fillna(0).astype(int)

# Cumulative sum of wickets per match
output['player_dismissed'] = output.groupby('match_id')['player_dismissed'].cumsum()

# Calculate wickets left
output['wickets_left'] = 10 - output['player_dismissed']

# Print results
print(output[['match_id', 'player_dismissed', 'wickets_left']])


# Check if the column exists before calling .value_counts()
if 'wickets_left' in output.columns:
    print(output[output['wickets_left'] == 10].value_counts())
else:
    print("Column 'wickets_left' not found in the DataFrame.")

       match_id  player_dismissed  wickets_left
0             2                 0            10
1             2                 0            10
2             2                 0            10
3             2                 0            10
4             2                 0            10
...         ...               ...           ...
56911       519                 9             1
56912       519                 9             1
56913       519                 9             1
56914       519                 9             1
56915       519                10             0

[56916 rows x 3 columns]
match_id  batting_team           bowling_team                 ball  runs_x  player_dismissed  city       venue                                      runs_y  current_runs  over  ball_no  balls_bowled  wickets_left
519       Sunrisers Hyderabad    Kolkata Knight Riders        0.4   2       0                 Chennai    MA Chidambaram Stadium, Chepauk, Chennai   113     2             0     4        4             10              1
2         Sunrisers Hyderabad    Royal Challengers Bengaluru  0.1   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     0             0     1        1             10              1
                                                              0.2   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     0             0     2        2             10              1
                                                              0.3   4       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     4             0     3        3             10              1
                                                              0.4   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     4             0     4        4             10              1
                                                                                                                                                                                                                      ..
8         Kolkata Knight Riders  Mumbai Indians               1.1   0       0                 Mumbai     Wankhede Stadium                           178     10            1     1        7             10              1
                                                              0.8   1       0                 Mumbai     Wankhede Stadium                           178     10            0     8        8             10              1
                                                              0.7   4       0                 Mumbai     Wankhede Stadium                           178     9             0     7        7             10              1
                                                              0.6   1       0                 Mumbai     Wankhede Stadium                           178     5             0     6        6             10              1
                                                              0.5   1       0                 Mumbai     Wankhede Stadium                           178     4             0     5        5             10              1
Name: count, Length: 11423, dtype: int64

In [76]:
output['crr'] = round((output['current_runs']*6)/output['balls_bowled'],2)

In [77]:
print(output.columns)  # Lists all columns in the DataFrame

Index(['match_id', 'batting_team', 'bowling_team', 'ball', 'runs_x',
       'player_dismissed', 'city', 'venue', 'runs_y', 'current_runs', 'over',
       'ball_no', 'balls_bowled', 'wickets_left', 'crr'],
      dtype='object')

In [78]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,venue,runs_y,current_runs,over,ball_no,balls_bowled,wickets_left,crr
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.1,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,0,0,1,1,10,0.00
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.2,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,0,0,2,2,10,0.00
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.3,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,4,0,3,3,10,8.00
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.4,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,4,0,4,4,10,6.00
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.5,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,6,0,5,5,10,7.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56911,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.5,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,17,5,107,1,6.34
56912,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.6,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,17,6,108,1,6.28
56913,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.1,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,1,109,1,6.22
56914,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.2,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,2,110,1,6.16
56915,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.3,0,10,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,3,111,0,6.11

In [79]:
output[output['wickets_left'] == 10].value_counts()

match_id  batting_team           bowling_team                 ball  runs_x  player_dismissed  city       venue                                      runs_y  current_runs  over  ball_no  balls_bowled  wickets_left  crr
519       Sunrisers Hyderabad    Kolkata Knight Riders        0.4   2       0                 Chennai    MA Chidambaram Stadium, Chepauk, Chennai   113     2             0     4        4             10            3.00    1
2         Sunrisers Hyderabad    Royal Challengers Bengaluru  0.1   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     0             0     1        1             10            0.00    1
                                                              0.2   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     0             0     2        2             10            0.00    1
                                                              0.3   4       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     4             0     3        3             10            8.00    1
                                                              0.4   0       0                 Hyderabad  Rajiv Gandhi International Stadium, Uppal  207     4             0     4        4             10            6.00    1
                                                                                                                                                                                                                            ..
8         Kolkata Knight Riders  Mumbai Indians               1.1   0       0                 Mumbai     Wankhede Stadium                           178     10            1     1        7             10            8.57    1
                                                              0.8   1       0                 Mumbai     Wankhede Stadium                           178     10            0     8        8             10            7.50    1
                                                              0.7   4       0                 Mumbai     Wankhede Stadium                           178     9             0     7        7             10            7.71    1
                                                              0.6   1       0                 Mumbai     Wankhede Stadium                           178     5             0     6        6             10            5.00    1
                                                              0.5   1       0                 Mumbai     Wankhede Stadium                           178     4             0     5        5             10            4.80    1
Name: count, Length: 11423, dtype: int64

In [80]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,venue,runs_y,current_runs,over,ball_no,balls_bowled,wickets_left,crr
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.1,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,0,0,1,1,10,0.00
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.2,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,0,0,2,2,10,0.00
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.3,4,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,4,0,3,3,10,8.00
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.4,0,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,4,0,4,4,10,6.00
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0.5,2,0,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",207,6,0,5,5,10,7.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56911,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.5,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,17,5,107,1,6.34
56912,519,Sunrisers Hyderabad,Kolkata Knight Riders,17.6,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,17,6,108,1,6.28
56913,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.1,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,1,109,1,6.22
56914,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.2,0,9,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,2,110,1,6.16
56915,519,Sunrisers Hyderabad,Kolkata Knight Riders,18.3,0,10,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",113,113,18,3,111,0,6.11

In [81]:
final_df = output[['match_id','batting_team','bowling_team','runs_x','current_runs','balls_bowled','wickets_left','crr','city','runs_y']]
final_df

,match_id,batting_team,bowling_team,runs_x,current_runs,balls_bowled,wickets_left,crr,city,runs_y
0,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,0,1,10,0.00,Hyderabad,207
1,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,0,2,10,0.00,Hyderabad,207
2,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,4,4,3,10,8.00,Hyderabad,207
3,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,4,4,10,6.00,Hyderabad,207
4,2,Sunrisers Hyderabad,Royal Challengers Bengaluru,2,6,5,10,7.20,Hyderabad,207
...,...,...,...,...,...,...,...,...,...,...
56911,519,Sunrisers Hyderabad,Kolkata Knight Riders,0,113,107,1,6.34,Chennai,113
56912,519,Sunrisers Hyderabad,Kolkata Knight Riders,0,113,108,1,6.28,Chennai,113
56913,519,Sunrisers Hyderabad,Kolkata Knight Riders,0,113,109,1,6.22,Chennai,113
56914,519,Sunrisers Hyderabad,Kolkata Knight Riders,0,113,110,1,6.16,Chennai,113
56915,519,Sunrisers Hyderabad,Kolkata Knight Riders,0,113,111,0,6.11,Chennai,113

In [82]:
final_df = final_df.sample(final_df.shape[0])
final_df['balls_left'] = 120 - final_df['balls_bowled']
final_df['balls_left'] = final_df['balls_left'].apply(lambda x:0 if x<0 else x)
final_df['crr'] = round((final_df['current_runs']*6)/final_df['balls_bowled'],2)
final_df

,match_id,batting_team,bowling_team,runs_x,current_runs,balls_bowled,wickets_left,crr,city,runs_y,balls_left
56216,514,Royal Challengers Bengaluru,Chennai Super Kings,1,52,42,10,7.43,Bengaluru,218,78
50394,467,Royal Challengers Bengaluru,Rajasthan Royals,1,156,105,7,8.91,Jaipur,183,15
2990,65,Kolkata Knight Riders,Chennai Super Kings,0,19,9,9,12.67,Chennai,202,111
8817,127,Mumbai Indians,Royal Challengers Bengaluru,0,55,41,9,8.05,Bengaluru,187,79
54574,501,Chennai Super Kings,Punjab Kings,1,12,10,10,7.20,Dharamsala,167,110
...,...,...,...,...,...,...,...,...,...,...,...
21759,234,Sunrisers Hyderabad,Kolkata Knight Riders,1,35,33,9,6.36,Abu Dhabi,142,87
17773,202,Punjab Kings,Chennai Super Kings,4,42,31,10,8.13,Dubai,178,89
21952,235,Delhi Capitals,Punjab Kings,2,137,101,7,8.14,Dubai,164,19
32722,323,Punjab Kings,Mumbai Indians,1,75,44,10,10.23,Pune,198,76
23814,250,Royal Challengers Bengaluru,Kolkata Knight Riders,0,148,101,7,8.79,Chennai,204,19

In [83]:
if 'balls_bowled' in final_df.columns:
    final_df = final_df.drop(columns=['balls_bowled'])

groups = final_df.groupby('match_id')

In [84]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_runs,wickets_left,crr,city,runs_y,balls_left
56216,514,Royal Challengers Bengaluru,Chennai Super Kings,1,52,10,7.43,Bengaluru,218,78
50394,467,Royal Challengers Bengaluru,Rajasthan Royals,1,156,7,8.91,Jaipur,183,15
2990,65,Kolkata Knight Riders,Chennai Super Kings,0,19,9,12.67,Chennai,202,111
8817,127,Mumbai Indians,Royal Challengers Bengaluru,0,55,9,8.05,Bengaluru,187,79
54574,501,Chennai Super Kings,Punjab Kings,1,12,10,7.20,Dharamsala,167,110
...,...,...,...,...,...,...,...,...,...,...
21759,234,Sunrisers Hyderabad,Kolkata Knight Riders,1,35,9,6.36,Abu Dhabi,142,87
17773,202,Punjab Kings,Chennai Super Kings,4,42,10,8.13,Dubai,178,89
21952,235,Delhi Capitals,Punjab Kings,2,137,7,8.14,Dubai,164,19
32722,323,Punjab Kings,Mumbai Indians,1,75,10,10.23,Pune,198,76
23814,250,Royal Challengers Bengaluru,Kolkata Knight Riders,0,148,7,8.79,Chennai,204,19

In [85]:
match_ids = final_df['match_id'].unique()
last_five = []

for id in match_ids:
    group = groups.get_group(id).copy()  # Explicitly create a copy to avoid the warning
    group.loc[:, 'runs_x'] = pd.to_numeric(group['runs_x'], errors='coerce')  # Safe modification
    last_five.extend(group.rolling(window=30)['runs_x'].sum().values.tolist())

In [86]:
final_df['last_five'] = last_five
final_df

,match_id,batting_team,bowling_team,runs_x,current_runs,wickets_left,crr,city,runs_y,balls_left,last_five
56216,514,Royal Challengers Bengaluru,Chennai Super Kings,1,52,10,7.43,Bengaluru,218,78,NaN
50394,467,Royal Challengers Bengaluru,Rajasthan Royals,1,156,7,8.91,Jaipur,183,15,NaN
2990,65,Kolkata Knight Riders,Chennai Super Kings,0,19,9,12.67,Chennai,202,111,NaN
8817,127,Mumbai Indians,Royal Challengers Bengaluru,0,55,9,8.05,Bengaluru,187,79,NaN
54574,501,Chennai Super Kings,Punjab Kings,1,12,10,7.20,Dharamsala,167,110,NaN
...,...,...,...,...,...,...,...,...,...,...,...
21759,234,Sunrisers Hyderabad,Kolkata Knight Riders,1,35,9,6.36,Abu Dhabi,142,87,64.0
17773,202,Punjab Kings,Chennai Super Kings,4,42,10,8.13,Dubai,178,89,67.0
21952,235,Delhi Capitals,Punjab Kings,2,137,7,8.14,Dubai,164,19,69.0
32722,323,Punjab Kings,Mumbai Indians,1,75,10,10.23,Pune,198,76,71.0
23814,250,Royal Challengers Bengaluru,Kolkata Knight Riders,0,148,7,8.79,Chennai,204,19,76.0

In [87]:
final_df.dropna(inplace=True)
final_df

,match_id,batting_team,bowling_team,runs_x,current_runs,wickets_left,crr,city,runs_y,balls_left,last_five
56886,519,Sunrisers Hyderabad,Kolkata Knight Riders,2,89,3,6.51,Chennai,113,38,51.0
26870,276,Rajasthan Royals,Mumbai Indians,1,48,7,5.76,Sharjah,90,70,51.0
29326,296,Royal Challengers Bengaluru,Chennai Super Kings,1,15,10,10.00,Sharjah,156,111,51.0
21239,230,Mumbai Indians,Rajasthan Royals,0,20,9,7.50,Abu Dhabi,195,104,51.0
54214,498,Sunrisers Hyderabad,Rajasthan Royals,0,25,9,6.00,Hyderabad,201,95,51.0
...,...,...,...,...,...,...,...,...,...,...,...
21759,234,Sunrisers Hyderabad,Kolkata Knight Riders,1,35,9,6.36,Abu Dhabi,142,87,64.0
17773,202,Punjab Kings,Chennai Super Kings,4,42,10,8.13,Dubai,178,89,67.0
21952,235,Delhi Capitals,Punjab Kings,2,137,7,8.14,Dubai,164,19,69.0
32722,323,Punjab Kings,Mumbai Indians,1,75,10,10.23,Pune,198,76,71.0
23814,250,Royal Challengers Bengaluru,Kolkata Knight Riders,0,148,7,8.79,Chennai,204,19,76.0

In [88]:
import xgboost
from xgboost import XGBRegressor
import sklearn

print(xgboost.__version__)
print(sklearn.__version__)

3.0.0
1.6.1

In [94]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# ✅ Assume final_df is already defined
# Define features and target
X = final_df.drop(columns=['match_id', 'runs_x', 'runs_y'])
y = final_df['runs_y']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Column transformer to handle categorical columns
trf = ColumnTransformer([
    ('ohe', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

# Pipeline with preprocessing + model
pipe = Pipeline(steps=[
    ('step1', trf),
    ('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

# Fit the model
pipe.fit(X_train, y_train)

# Predict and evaluate
y_pred = pipe.predict(X_test)
print("R² Score:", r2_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))

R² Score: 0.9274349212646484
Mean Absolute Error: 4.152128219604492